set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -g focus-events on
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm*:Tc"
set -g mouse on

# actually, we need to set extended-keys enable but it has a bug with neovim.
# this is a workaround by remapping shift+enter to ctrl+j.
bind-key -T root S-Enter send-keys C-j

# mouse wheel event bypass for neovim
bind -n WheelUpPane  if-shell -F 'ps -t "#{pane_tty}" -o comm= | grep -Eq "^n?vim$"'  'send-keys -M' 'copy-mode -e'
bind -n WheelDownPane if-shell -F 'ps -t "#{pane_tty}" -o comm= | grep -Eq "^n?vim$"' 'send-keys -M' 'copy-mode -e'

# SSH authentication socket bypassing
set-environment -g -u SSH_AUTH_SOCK
